local Roact = require(shared.DevTrack.Packages.Roact)

local function LoginForm(props)
	return Roact.createElement("Frame", {
		Name = "LoginForm",
		AnchorPoint = props.AnchorPoint,
		Position = props.Position,
		Size = props.Size,
		BackgroundTransparency = 1,
	}, {
		Title = Roact.createElement("TextLabel", {
			Name = "Title",
			Position = UDim2.new(0, 0, 0, 0),
			Size = UDim2.new(1, 0, 0, 32),
			BackgroundTransparency = 1,
			Font = Enum.Font.RobotoMono,
			TextSize = 32,
			TextColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.MainText),
			Text = "LOGIN",
		}),

		Fields = Roact.createElement("Frame", {
			Name = "Fields",
			AnchorPoint = Vector2.new(0, 0.5),
			Position = UDim2.new(0, 0, 0.5, 0),
			Size = UDim2.new(1, 0, 0, 152),
			BackgroundTransparency = 1,
		}, {
			EmailField = Roact.createElement("Frame", {
				Name = "EmailField",
				Position = UDim2.new(0, 0, 0, 0),
				Size = UDim2.new(1, 0, 0, 68),
				BackgroundTransparency = 1,
			}, {
				Label = Roact.createElement("TextLabel", {
					Name = "Label",
					Position = UDim2.new(0, 0, 0, 0),
					Size = UDim2.new(1, 0, 0, 16),
					BackgroundTransparency = 1,
					TextColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.SubText),
					Font = Enum.Font.RobotoMono,
					TextSize = 16,
					TextXAlignment = Enum.TextXAlignment.Left,
					Text = "Email",
				}),
				Input = Roact.createElement("TextBox", {
					Name = "Input",
					Position = UDim2.new(0, 0, 0, 24),
					Size = UDim2.new(1, 0, 0, 24),
					BorderColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.InputFieldBorder),
					BackgroundColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.InputFieldBackground),
					TextColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.MainText),
					Font = Enum.Font.RobotoMono,
					TextSize = 24,
					TextXAlignment = Enum.TextXAlignment.Left,
					TextTruncate = Enum.TextTruncate.AtEnd,
					PlaceholderText = "example@gmail.com",
					Text = "",
				}),
				Feedback = Roact.createElement("TextLabel", {
					Name = "Feedback",
					AnchorPoint = Vector2.new(0, 1),
					Position = UDim2.new(0, 0, 1, 0),
					Size = UDim2.new(1, 0, 0, 12),
					BackgroundTransparency = 1,
					TextColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.ErrorText),
					Font = Enum.Font.RobotoMono,
					TextSize = 12,
					TextXAlignment = Enum.TextXAlignment.Left,
					Text = "Something went wrong...",
				}),
			}),
			PasswordField = Roact.createElement("Frame", {
				Name = "PasswordField",
				AnchorPoint = Vector2.new(0, 1),
				Position = UDim2.new(0, 0, 1, 0),
				Size = UDim2.new(1, 0, 0, 68),
				BackgroundTransparency = 1,
			}, {
				Label = Roact.createElement("TextLabel", {
					Name = "Label",
					Position = UDim2.new(0, 0, 0, 0),
					Size = UDim2.new(1, 0, 0, 16),
					BackgroundTransparency = 1,
					TextColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.SubText),
					Font = Enum.Font.RobotoMono,
					TextSize = 16,
					TextXAlignment = Enum.TextXAlignment.Left,
					Text = "Password",
				}),
				Input = Roact.createElement("TextBox", {
					Name = "Input",
					Position = UDim2.new(0, 0, 0, 24),
					Size = UDim2.new(1, 0, 0, 24),
					BorderColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.InputFieldBorder),
					BackgroundColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.InputFieldBackground),
					TextColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.MainText),
					Font = Enum.Font.RobotoMono,
					TextSize = 24,
					TextXAlignment = Enum.TextXAlignment.Left,
					TextTruncate = Enum.TextTruncate.AtEnd,
					Text = "",
				}),
				Feedback = Roact.createElement("TextLabel", {
					Name = "Feedback",
					AnchorPoint = Vector2.new(0, 1),
					Position = UDim2.new(0, 0, 1, 0),
					Size = UDim2.new(1, 0, 0, 12),
					BackgroundTransparency = 1,
					TextColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.ErrorText),
					Font = Enum.Font.RobotoMono,
					TextSize = 12,
					TextXAlignment = Enum.TextXAlignment.Left,
					Text = "Something went wrong...",
				}),
			}),
		}),

		LoginButton = Roact.createElement("TextButton", {
			Name = "LoginButton",
			AnchorPoint = Vector2.new(0, 1),
			Position = UDim2.new(0, 0, 1, 0),
			Size = UDim2.new(1, 0, 0, 24),
			BackgroundColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.Button),
			BorderColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.ButtonBorder),
			Font = Enum.Font.RobotoMono,
			TextSize = 24,
			TextColor3 = settings().Studio.Theme:GetColor(Enum.StudioStyleGuideColor.ButtonText),
			Text = "Login",
		}),
	})
end

return LoginForm
